services:
  - type: web
    name: gm-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://gm-backend.onrender.com  # backend API URL
