"""Add sold_by column to sales

Revision ID: 597e01928a18
Revises: 7a36c88846be
Create Date: 2025-08-26 05:47:14.969442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597e01928a18'
down_revision = '7a36c88846be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('sold_by')

    # ### end Alembic commands ###
