"""Add sold_price columns to Joint and Inventory

Revision ID: 7a36c88846be
Revises: e2ebc69d1aea
Create Date: 2025-08-25 10:43:10.786534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a36c88846be'
down_revision = 'e2ebc69d1aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_price', sa.Float(), nullable=True))

    with op.batch_alter_table('joints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joints', schema=None) as batch_op:
        batch_op.drop_column('sold_price')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('sold_price')

    # ### end Alembic commands ###
