"""Add buying_price to Inventory

Revision ID: d95bcaf5a894
Revises: 597e01928a18
Create Date: 2025-08-26 12:16:29.295150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95bcaf5a894'
down_revision = '597e01928a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buying_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('buying_price')

    # ### end Alembic commands ###
