"""Add ended_at and assigned_to to joints

Revision ID: e2ebc69d1aea
Revises: f5102cc4459e
Create Date: 2025-08-25 05:40:52.768964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ebc69d1aea'
down_revision = 'f5102cc4459e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('joints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joints', schema=None) as batch_op:
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('ended_at')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###
